apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  namespace: sinosdx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      containers:
      - name: service-auth
        image: registry.cn-shanghai.aliyuncs.com/sinosdx/api-service-auth:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8094
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: service-auth
  namespace: sinosdx-api
spec:
  ports:
    - port: 8094
      targetPort: 8094
      protocol: TCP
  selector:
    app: service-auth
---
apiVersion: v1
kind: Service
metadata:
  name: service-auth-nodeport
  namespace: sinosdx-api
spec:
  type: NodePort
  ports:
    - port: 8094
      targetPort: 8094
      nodePort: 30004
  selector:
    app: service-auth
