apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-user
  namespace: sinosdx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-user
  template:
    metadata:
      labels:
        app: service-user
    spec:
      containers:
      - name: service-user
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8093
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: service-user
  namespace: sinosdx-api
spec:
  ports:
    - port: 8093
      targetPort: 8093
      protocol: TCP
  selector:
    app: service-user
---
apiVersion: v1
kind: Service
metadata:
  name: service-user-nodeport
  namespace: sinosdx-api
spec:
  type: NodePort
  ports:
    - port: 8093
      targetPort: 8093
      nodePort: 30002
  selector:
    app: service-user
