apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sinosdx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: registry.cn-shanghai.aliyuncs.com/sinosdx/api-api-gateway:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 18765
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sinosdx-api
spec:
  ports:
    - port: 18765
      targetPort: 18765
      protocol: TCP
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nodeport
  namespace: sinosdx-api
spec:
  type: NodePort
  ports:
    - port: 18765
      targetPort: 18765
      nodePort: 30001
  selector:
    app: api-gateway
