apiVersion: v1
kind: Service
metadata:
  name: openresty
  namespace: sinosdx-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80 
      nodePort: 30000
  selector:
    app: openresty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty
  namespace: sinosdx-api
spec:
  selector:
    matchLabels:
      app: openresty
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/sinosdx/openresty:prod 
        name: openresty 
        ports:
        - containerPort: 80 
          name: openresty
