apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: sinosdx-api
spec:
  type: NodePort
  ports:
    - port: 8848 
      targetPort: 8848 
      nodePort: 30848
  selector:
    app: nacos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: sinosdx-api
spec:
  selector:
    matchLabels:
      app: nacos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nacos
    spec:
      nodeSelector:
        deployrole2: nacos 
      containers:
      - image: nacos/nacos-server:v2.0.3 
        name: nacos
        ports:
        - containerPort: 8848
          name: nacos
        env:
          - name: MODE 
            value: standalone
        volumeMounts:
        - name: nacos-persistent-storage
          mountPath: /home/nacos
      volumes:
      - name: nacos-persistent-storage
        hostPath:
            path: /data/nacos
            type: Directory
