#
# Copyright © 2022 SinoSDX (biz@sinosdx.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  namespace: sinosdx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      containers:
      - name: service-auth
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8094
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: service-auth
  namespace: sinosdx-api
spec:
  ports:
    - port: 8094
      targetPort: 8094
      protocol: TCP
  selector:
    app: service-auth
---
apiVersion: v1
kind: Service
metadata:
  name: service-auth-nodeport
  namespace: sinosdx-api
spec:
  type: NodePort
  ports:
    - port: 8094
      targetPort: 8094
      nodePort: 30004
  selector:
    app: service-auth
