apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-api-management
  namespace: sinosdx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-api-management
  template:
    metadata:
      labels:
        app: service-api-management
    spec:
      containers:
      - name: service-api-management
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8095
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: service-api-management
  namespace: sinosdx-api
spec:
  ports:
    - port: 8095
      targetPort: 8095
      protocol: TCP
  selector:
    app: service-api-management
---
apiVersion: v1
kind: Service
metadata:
  name: service-api-management-nodeport
  namespace: sinosdx-api
spec:
  type: NodePort
  ports:
    - port: 8095
      targetPort: 8095
      nodePort: 30005
  selector:
    app: service-api-management
