apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-web-api-management
  namespace: sinosdx-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-web-api-management
  template:
    metadata:
      labels:
        app: api-web-api-management
    spec:
      containers:
      - name: api-web-api-management
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: api-web-api-management
  namespace: sinosdx-api
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: api-web-api-management
---
apiVersion: v1
kind: Service
metadata:
  name: api-web-api-management-nodeport
  namespace: sinosdx-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30138
  selector:
    app: api-web-api-management
