version: '3'
# 如果执行失败,请选尝试创建 docker network create sino-apix
#networks:
#  default:
#    driver: bridge
#    external:
#      name: sino-apix
services:
  nacos:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/nacos:2.0.3
    container_name: apix-nacos
    restart: always
    ports:
      - 8848:8848
  mysql:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/mysql:5.7
    container_name: apix-mysql
    restart: always
    ports:
      - 3306:3306
  redis:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/redis:3.2.8
    container_name: apix-redis
    restart: always
    ports:
      - 6379:6379
  openresty:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/openresty:prod
    container_name: apix-openresty
    restart: always
    depends_on:
      - nacos
      - mysql
      - redis
    ports:
      - 8080:8080
  service-gateway:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/api-api-gateway:latest
    container_name: apix-service-gateway
    restart: always
    ports:
      - 18765:18765
    environment:
      - JAVA_OPTS=-server -XX:+PrintGCDetails -XX:+PrintHeapAtGC -Xloggc:gc.log \
        -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms1024m -Xmx1024m -Xmn512m -Xss256k -XX:SurvivorRatio=8 \
        -XX:+UseConcMarkSweepGC
    depends_on:
      - nacos
      - mysql
      - redis
  service-user:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/api-service-user:latest
    container_name: apix-service-user
    restart: always
    ports:
      - 8093:8093
    environment:
      - JAVA_OPTS=-server -Xmx512m -Xms512m
    depends_on:
      - nacos
      - mysql
      - redis
  service-auth:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/api-service-auth:latest
    container_name: apix-service-auth
    restart: always
    ports:
      - 8094:8094
    environment:
      - JAVA_OPTS=-server -Xmx512m -Xms512m
    depends_on:
      - nacos
      - mysql
      - redis
  service-api-management:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/api-service-api-management:latest
    container_name: apix-service-api-management
    restart: always
    ports:
      - 8095:8095
    environment:
      - JAVA_OPTS=-server -Xmx512m -Xms512m
    depends_on:
      - nacos
      - mysql
      - redis
  service-support-log:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/api-service-support-log:latest
    container_name: apix-service-support-log
    restart: always
    ports:
      - 9021:9021
    environment:
      - JAVA_OPTS=-server -Xmx512m -Xms512m
    depends_on:
      - nacos
      - mysql
      - redis
  web:
    image: registry.cn-shanghai.aliyuncs.com/sinosdx/api-web-api-management:latest
    container_name: apix-web
    restart: always
    ports:
      - 80:80
