FROM  registry.cn-shanghai.aliyuncs.com/sinosdx/openresty
RUN mkdir -p  /etc/nginx/logs/
COPY default.conf /etc/nginx/conf.d/

#docker build -t registry.cn-shanghai.aliyuncs.com/sinosdx/openresty:prod .
