version: '3'
services:
  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    container_name: redis
  nacos:
    container_name: nacos
    image: nacos/nacos-server:2.0.3
    environment:
      MODE: standalone
      JVM_XMS: 512m
      JVM_MMS: 320m
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    restart: always
